version: '3'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - fast_msg_net
    depends_on:
      - redis
      - postgres

  celery:
    build: .
    container_name: celery_worker
    command: celery -A core.celery_tasks:app worker --loglevel=info --pool=solo
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - fast_msg_net
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - fast_msg_net

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fast_msg_net

volumes:
  postgres_data:

networks:
  fast_msg_net: